{
 "title": "מצלמות זמן אמת",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "התראות לאורך זמן",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(datetime, '1h'),\r\n  count(truck_class) AS \"count\"\r\nFROM events\r\nWHERE\r\n  $__timeFilter(datetime)\r\nGROUP BY 1\r\nORDER BY 1"
    }
   ]
  },
  {
   "title": "התראות לאורך זמן לפי מספר השורות",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(datetime, '1h'),\r\n  100*count(truck_class) / count(id) AS \"alerts/count\"\r\nFROM events\r\nWHERE\r\n  $__timeFilter(datetime)\r\nGROUP BY 1\r\nORDER BY 1"
    }
   ]
  },
  {
   "title": "לוח התראות",
   "type": "table",
   "gridPos": { "h": 20, "w": 13, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT id, truck_class AS \"Truck\", datetime AS \"Time\", probability AS \"Probability\", camera_name AS \"Camera\", CONCAT('https://waste-reduction.s3.eu-west-1.amazonaws.com/', REPLACE(s3_uri, 's3://waste-reduction/','')) as \"Image\"\r\nFROM events WHERE truck_class IS NOT NULL AND $__timeFilter(datetime) ORDER BY datetime DESC"
    }
   ]
  },
  {
   "title": "מספר המשאיות לפי מצלמה",
   "type": "barchart",
   "gridPos": { "h": 20, "w": 11, "x": 13, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT camera_name,\r\nCOUNT(truck_class), \r\ntruck_class, \r\nCONCAT(camera_name, '  ',truck_class)\r\nFROM events\r\nWHERE $__timeFilter(datetime) \r\nGROUP BY camera_name, truck_class, CONCAT(camera_name, truck_class)\r\nORDER BY CONCAT(camera_name, '  ',truck_class)"
    },
    {}
   ]
  },
  {
   "title": "מספר התראות כולל",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(truck_class) FROM events WHERE $__timeFilter(datetime) "
    }
   ]
  },
  {
   "title": "סה\"כ התראות למצלמה",
   "type": "table",
   "gridPos": { "h": 9, "w": 9, "x": 6, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT camera_name AS \"Camera\", truck_class AS \"Truck\", COUNT(*) AS \"Count\", avg(probability) AS \"Average probability\" FROM events WHERE $__timeFilter(datetime) GROUP BY camera_name, truck_class ORDER BY camera_name DESC"
    }
   ]
  },
  {
   "title": "התראות למצלמה",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  camera_name, count (truck_class)\r\nFROM events\r\nWHERE\r\n  $__timeFilter(datetime)\r\nGROUP BY camera_name"
    }
   ]
  },
  {
   "title": "לא מכוסה",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(truck_class) FROM events WHERE truck_class = 'uncovered' AND $__timeFilter(datetime) "
    }
   ]
  },
  {
   "title": "מכוסה",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(truck_class) FROM events WHERE truck_class = 'covered' AND $__timeFilter(datetime)"
    }
   ]
  },
  {
   "title": "אחר",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(truck_class) FROM events WHERE truck_class = 'other' AND $__timeFilter(datetime) "
    }
   ]
  },
  {
   "title": "אין התראות",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(id) - count(truck_class) FROM events WHERE $__timeFilter(datetime) "
    }
   ]
  },
  {
   "title": "מידע גולמי",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {
     "rawSql": "SELECT * FROM events ORDER BY id DESC"
    }
   ]
  }
 ]
}